version "3.7"

services:
    hitmeapp-backend:
        build: .
        restart: unless-stopped
        ports:
            - 5000:80
        networks:
            - hitmeapp
        depends_on:
            - hitmeapp-db

    hitmeapp-db:
        build: ./DB
        restart: unless-stopped
        networks:
            - hitmeapp

networks:
    hitmeapp:
        name: hitmeapp-network
        external: true
