version: "3.8"

services:
    hitmeapp-backend:
        build: .
        restart: unless-stopped
        ports:
            - 5000:80
        networks:
            - hitmeapp
        depends_on:
            - hitmeapp-db

    hitmeapp-db:
        build: ./DB
        restart: unless-stopped
        ports:
            - 5432:5432
        networks:
            - hitmeapp
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: hitmeapp

networks:
    hitmeapp:
        name: hitmeapp-network
        driver: bridge
