# Install REST Client extension for VS Code created by Huachao Mao to use this file correctly

# ******************************************************* #
# ------------------------ Global ----------------------- #
# ******************************************************* #

@url = http://localhost:5000
@userId = {{RegisterUser.response.body.id}}

@accessToken = {{UserLogIn.response.body.accessToken}}

# ******************************************************* #
# ---------------------- Identity ----------------------- #
# ******************************************************* #

@identityUrl = {{url}}/identity

###
# @name RegisterUser
POST {{identityUrl}}/register
Content-Type: application/json

{
    "email": "test@hitmeapp.com",
    "password": "Secret123$"
}

###
# @name GetUserById
GET {{identityUrl}}/{{userId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
}

###
# @name ChangeUserPassword
PATCH {{identityUrl}}/{{userId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "CurrentPassword": "Secret123$",
    "NewPassword": "NewSecret123$"
}

###
# @name UserLogIn
POST {{identityUrl}}/login
Content-Type: application/json

{
    "email": "test@hitmeapp.com",
    "password": "Secret123$"
}

# ******************************************************* #
# ---------------------- Users -------------------------- #
# ******************************************************* #

@usersUrl = {{url}}/users

###
# @name ChangePersonalInfo
PUT {{usersUrl}}/{{userId}}/personal-info
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nickname": "SampleUser",
    "description": "Some description about me",
    "birthDate": "1920-05-18T21:37:00",
    "sex": 1
}

###
# @name ChangeLocation
PUT {{usersUrl}}/{{userId}}/location
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "latitude": 41.902222222222,
    "longitude": 12.456388888889
}