name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  branch-convention-check:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: deepakputhraya/action-branch-name@master
      with:
        regex: '^([a-z]+)\/([a-z0-9]+(?:-[a-z0-9]+)*)'
        allowed_prefixes: 'feature,release,bugfix'
        ignore: main,develop
        min_length: 3
        max_length: 100
    - name: Trigger next workflow
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: main-workflow-passed
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
